# Generated by Django 5.1.5 on 2026-05-16 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deviceinfo",
            options={"ordering": ["-activation_date"]},
        ),
        migrations.AlterModelOptions(
            name="serialkey",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="deviceinfo",
            name="device_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="serialkey",
            name="key",
            field=models.CharField(
                help_text="16-character uppercase alphanumeric serial key.",
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Serial keys must be 16 uppercase letters or digits.",
                        regex="^[A-Z0-9]{16}$",
                    )
                ],
            ),
        ),
    ]
